import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeModeScript } from 'flowbite-react';
import './globals.css';
import Sidebar from '../components/Sidebar';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Flowbite React',
  description: 'Generated by create flowbite react',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} flex min-h-screen bg-gray-100 dark:bg-gray-800`}
      >
        <Sidebar />
        <main className="flex-1 p-6 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
