import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ThemeModeScript} from "flowbite-react";
import "./globals.css";
import {SidebarLayout, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alma Back Office",
  description: "Generated by Alma-Spec Wizard",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { cookies } = await import("next/headers")
  return (
    <html lang="en">
    <head>
        <title>Alma Back Office</title>
        <ThemeModeScript/>
    </head>
      <body className={`${inter.className}`}>
      <SidebarLayout
          defaultOpen={cookies().get("sidebar:state")?.value === "true"}
      >
        <AppSidebar />
        <main className="flex flex-1 flex-col p-2 transition-all duration-300 ease-in-out">
          <div className="h-full rounded-md border-2 border-dashed p-2">
            {children}
          </div>
        </main>
      </SidebarLayout>
      </body>
    </html>
  );
}
